#!/usr/bin/env python3
"""
Envoy DRR Dispatcher Goodput Visualization Script.

Parses CSV results generated by `drr_goodput_experiment` and generates:
1. High-resolution SVG comparative chart (`drr_goodput_comparison.svg`)
2. Self-contained HTML report with embedded SVG and metrics table (`drr_goodput_comparison.html`)
3. ASCII line graph rendered to terminal output.
"""

import argparse
import csv
import math
import os
import sys
from typing import Dict, List, Tuple

COLORS = {
    "WellBehaved-1": "#1b9e77",  # Green
    "WellBehaved-2": "#377eb8",  # Blue
    "NoisyNeighbor-1": "#e41a1c",  # Red
    "WellBehaved-3": "#984ea3",  # Purple
    "NoisyNeighbor-2": "#ff7f00",  # Orange
}
DEFAULT_COLOR = "#666666"


class DataPoint:
  def __init__(
      self,
      time_ms: float,
      tenant_id: int,
      tenant_name: str,
      tenant_type: str,
      goodput: float,
      target: float,
  ):
    self.time_ms = time_ms
    self.tenant_id = tenant_id
    self.tenant_name = tenant_name
    self.tenant_type = tenant_type
    self.goodput = goodput
    self.target = target


def load_csv(path: str) -> Dict[str, List[DataPoint]]:
  if not os.path.exists(path):
    print(f"Error: CSV file '{path}' not found.", file=sys.stderr)
    sys.exit(1)

  series: Dict[str, List[DataPoint]] = {}
  with open(path, mode="r", newline="") as f:
    reader = csv.DictReader(f)
    for row in reader:
      name = row["tenant_name"]
      dp = DataPoint(
          time_ms=float(row["time_ms"]),
          tenant_id=int(row["tenant_id"]),
          tenant_name=name,
          tenant_type=row["tenant_type"],
          goodput=float(row["goodput_ops_per_sec"]),
          target=float(row["target_ops_per_sec"]),
      )
      if name not in series:
        series[name] = []
      series[name].append(dp)
  return series


def generate_svg(
    legacy_data: Dict[str, List[DataPoint]],
    drr_data: Dict[str, List[DataPoint]],
    title: str,
    output_path: str,
) -> None:
  width = 1100
  height = 460
  margin_top = 60
  margin_bottom = 60
  margin_left = 70
  margin_right = 30
  panel_gap = 60

  panel_w = (width - margin_left - margin_right - panel_gap) / 2
  panel_h = height - margin_top - margin_bottom

  max_time = 0.0
  max_val = 0.0
  for series in (legacy_data, drr_data):
    for points in series.values():
      for pt in points:
        if pt.time_ms > max_time:
          max_time = pt.time_ms
        if pt.goodput > max_val:
          max_val = pt.goodput
  max_time = max(max_time, 1000.0)
  max_val = max(max_val, 1000.0)
  max_val = math.ceil(max_val / 5000.0) * 5000.0

  svg = [
      f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}"'
      ' width="100%" height="100%" style="font-family:'
      ' Arial, sans-serif; background: #ffffff;">'
  ]
  svg.append(
      f'<text x="{width/2}" y="30" text-anchor="middle" font-size="18"'
      f' font-weight="bold" fill="#222">{title}</text>'
  )

  def draw_panel(
      data: Dict[str, List[DataPoint]], offset_x: float, panel_title: str
  ) -> None:
    # Panel title
    svg.append(
        f'<text x="{offset_x + panel_w/2}" y="{margin_top - 15}"'
        ' text-anchor="middle" font-size="14" font-weight="bold"'
        f' fill="#333">{panel_title}</text>'
    )

    # Background border
    svg.append(
        f'<rect x="{offset_x}" y="{margin_top}" width="{panel_w}"'
        f' height="{panel_h}" fill="#fcfcfc" stroke="#dddddd" stroke-width="1"/>'
    )

    # Grid lines and Y labels
    num_y_ticks = 5
    for i in range(num_y_ticks + 1):
      val = max_val * i / num_y_ticks
      y = margin_top + panel_h - (i / num_y_ticks * panel_h)
      svg.append(
          f'<line x1="{offset_x}" y1="{y}" x2="{offset_x + panel_w}" y2="{y}"'
          ' stroke="#eeeeee" stroke-width="1"/>'
      )
      if offset_x == margin_left:
        svg.append(
            f'<text x="{offset_x - 10}" y="{y + 4}" text-anchor="end"'
            f' font-size="11" fill="#555">{int(val)}</text>'
        )

    # X axis labels
    num_x_ticks = 5
    for i in range(num_x_ticks + 1):
      t = max_time * i / num_x_ticks
      x = offset_x + (i / num_x_ticks * panel_w)
      svg.append(
          f'<line x1="{x}" y1="{margin_top + panel_h}" x2="{x}"'
          f' y2="{margin_top + panel_h + 5}" stroke="#999999" stroke-width="1"/>'
      )
      svg.append(
          f'<text x="{x}" y="{margin_top + panel_h + 18}" text-anchor="middle"'
          f' font-size="11" fill="#555">{int(t)} ms</text>'
      )

    # Phase boundary lines and labels
    for ratio, label in [(1/3, "10s (Ramp Start)"), (2/3, "20s (Ramp Complete)")]:
      x_line = offset_x + ratio * panel_w
      svg.append(
          f'<line x1="{x_line}" y1="{margin_top}" x2="{x_line}"'
          f' y2="{margin_top + panel_h}" stroke="#cccccc" stroke-width="1.5"'
          ' stroke-dasharray="4 4"/>'
      )
      svg.append(
          f'<text x="{x_line}" y="{margin_top - 4}" text-anchor="middle"'
          f' font-size="10" fill="#777">{label}</text>'
      )

    # Lines
    for name, points in data.items():
      color = COLORS.get(name, DEFAULT_COLOR)
      coords = []
      for pt in points:
        x = offset_x + (pt.time_ms / max_time) * panel_w
        y = margin_top + panel_h - (pt.goodput / max_val) * panel_h
        coords.append(f"{x:.1f},{y:.1f}")
      points_str = " ".join(coords)
      svg.append(
          f'<polyline fill="none" stroke="{color}" stroke-width="2.5"'
          f' points="{points_str}"/>'
      )

  # Draw Legacy FIFO (Left) and DRR (Right) panels
  draw_panel(
      legacy_data, margin_left, "Legacy FIFO Dispatcher (Noisy Neighbor Starvation)"
  )
  draw_panel(
      drr_data,
      margin_left + panel_w + panel_gap,
      "DRR Dispatcher (Fair Multi-Tenant Slicing)",
  )

  # Legend
  legend_x = width / 2 - 200
  legend_y = height - 15
  idx = 0
  for name in drr_data.keys():
    color = COLORS.get(name, DEFAULT_COLOR)
    x = legend_x + idx * 140
    svg.append(
        f'<rect x="{x}" y="{legend_y - 10}" width="12" height="12"'
        f' fill="{color}"/>'
    )
    svg.append(
        f'<text x="{x + 18}" y="{legend_y}" font-size="12"'
        f' fill="#333">{name}</text>'
    )
    idx += 1

  svg.append("</svg>")
  with open(output_path, "w") as f:
    f.write("\n".join(svg))
  print(f"Wrote comparative SVG graph to: {output_path}")


def generate_html(
    legacy_data: Dict[str, List[DataPoint]],
    drr_data: Dict[str, List[DataPoint]],
    svg_path: str,
    output_path: str,
) -> None:
  with open(svg_path, "r") as f:
    svg_content = f.read()

  html = [
      "<!DOCTYPE html>",
      "<html><head><meta charset='utf-8'>",
      "<title>Envoy DRR Dispatcher Goodput Report</title>",
      """<style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 40px; background: #f8f9fa; color: #212529; }
        .container { max-width: 1100px; margin: 0 auto; background: #fff; padding: 30px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
        h1 { font-size: 24px; margin-bottom: 10px; }
        p.subtitle { color: #6c757d; margin-bottom: 30px; }
        .chart-container { margin-bottom: 40px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { padding: 12px 15px; text-align: left; border-bottom: 1px solid #dee2e6; }
        th { background-color: #f1f3f5; font-weight: 600; }
        .badge-good { background: #d4edda; color: #155724; padding: 4px 8px; border-radius: 4px; font-weight: bold; }
        .badge-bad { background: #f8d7da; color: #721c24; padding: 4px 8px; border-radius: 4px; font-weight: bold; }
        </style></head><body>
        <div class="container">
          <h1>Envoy Dispatcher Goodput Analysis: Legacy FIFO vs. DRR Dispatcher</h1>
          <p class="subtitle">Multi-Tenant Fairness under Noisy Neighbor Contention</p>
          <div class="chart-container">
    """,
      svg_content,
      """</div>
          <h2>Quantitative Summary (Final Stable Goodput)</h2>
          <table>
            <thead>
              <tr>
                <th>Tenant Name</th>
                <th>Tenant Type</th>
                <th>Target Rate (ops/s)</th>
                <th>Legacy FIFO Goodput (ops/s)</th>
                <th>DRR Goodput (ops/s)</th>
                <th>Fairness Assessment</th>
              </tr>
            </thead>
            <tbody>
    """,
  ]

  for name in drr_data.keys():
    l_pt = legacy_data[name][-1]
    d_pt = drr_data[name][-1]
    is_well_behaved = "well_behaved" in d_pt.tenant_type
    l_good = l_pt.goodput
    d_good = d_pt.goodput

    if is_well_behaved:
      badge = (
          '<span class="badge-good">PROTECTED (100% Goodput)</span>'
          if d_good >= d_pt.target * 0.95
          else '<span class="badge-bad">STARVED</span>'
      )
    else:
      badge = '<span class="badge-good">FAIRLY THROTTLED</span>'

    html.append(f"""
      <tr>
        <td><strong>{name}</strong></td>
        <td>{d_pt.tenant_type}</td>
        <td>{int(d_pt.target):,}</td>
        <td>{l_good:,.1f}</td>
        <td><strong>{d_good:,.1f}</strong></td>
        <td>{badge}</td>
      </tr>
    """)

  html.append("""
            </tbody>
          </table>
        </div>
      </body>
      </html>
    """)

  with open(output_path, "w") as f:
    f.write("\n".join(html))
  print(f"Wrote HTML visual report to: {output_path}")


def print_ascii_chart(
    legacy_data: Dict[str, List[DataPoint]],
    drr_data: Dict[str, List[DataPoint]],
) -> None:
  max_ts = max(pt.time_ms for points in drr_data.values() for pt in points)
  checkpoints = (
      [10000.0, 20000.0, 30000.0]
      if max_ts == 30000.0
      else [max_ts / 3, (2 * max_ts) / 3, max_ts]
  )
  phase_labels = [
      "PHASE 1 (t = 10s): Equal Demand (6,000 ops/s for all tenants)",
      "PHASE 2 (t = 20s): Noisy Neighbor Demand Ramped Up to 50,000 ops/s",
      "PHASE 3 (t = 30s): Sustained Heavy Contention (50,000 ops/s)",
  ]

  for idx, ts in enumerate(checkpoints):
    label = phase_labels[idx] if idx < len(phase_labels) else f"t = {int(ts)} ms"
    print(f"\nASCII GOODPUT COMPARISON - {label}:")
    print("-" * 75)
    for name in drr_data.keys():
      # Find point closest to timestamp ts
      l_pt = min(
          legacy_data[name], key=lambda p, target=ts: abs(p.time_ms - target)
      )
      d_pt = min(
          drr_data[name], key=lambda p, target=ts: abs(p.time_ms - target)
      )

      l_val = l_pt.goodput
      d_val = d_pt.goodput
      target = d_pt.target

      l_bars = "#" * min(int(l_val / 500), 40)
      d_bars = "#" * min(int(d_val / 500), 40)

      print(f"{name} (Target Demand: {target:,.0f} ops/s):")
      print(f"  Legacy FIFO : {l_val:8,.1f} | {l_bars}")
      print(f"  DRR Dispatch: {d_val:8,.1f} | {d_bars}")
    print("-" * 75)
  print()


def main():
  parser = argparse.ArgumentParser(
      description="Envoy DRR Dispatcher Goodput Visualization Tool"
  )
  parser.add_argument(
      "--legacy_csv",
      default="/tmp/drr_experiment/goodput_legacy.csv",
      help="Path to Legacy FIFO CSV results",
  )
  parser.add_argument(
      "--drr_csv",
      default="/tmp/drr_experiment/goodput_drr.csv",
      help="Path to DRR Dispatcher CSV results",
  )
  parser.add_argument(
      "--output_svg",
      default="/tmp/drr_experiment/drr_goodput_comparison.svg",
      help="Path to write generated SVG chart",
  )
  parser.add_argument(
      "--output_html",
      default="/tmp/drr_experiment/drr_goodput_comparison.html",
      help="Path to write generated HTML report",
  )
  parser.add_argument(
      "--title",
      default="Envoy Dispatcher Goodput: Legacy FIFO vs. DRR Dispatcher",
      help="Title for the generated chart",
  )
  parser.add_argument(
      "--no_ascii", action="store_true", help="Suppress ASCII terminal chart"
  )

  args = parser.parse_args()

  legacy_data = load_csv(args.legacy_csv)
  drr_data = load_csv(args.drr_csv)

  os.makedirs(os.path.dirname(args.output_svg), exist_ok=True)
  generate_svg(legacy_data, drr_data, args.title, args.output_svg)
  generate_html(legacy_data, drr_data, args.output_svg, args.output_html)

  if not args.no_ascii:
    print_ascii_chart(legacy_data, drr_data)


if __name__ == "__main__":
  main()
